// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/www.proto
package remotecli

import "fmt"

func (c *remoteCli) cmdHelp(args []string) (string, error) {
	h := `HELP :

	┌─ version
	└─ call version service

	┌─ services_status
	└─ call services_status service

	┌─ echo <uuid [string]> <content [string]>
	└─ call echo service

	┌─ service_address
	└─ return service address

	┌─ jwt [<token>]
	└─ display current jwt or save one if it's set

	┌─ default_timeout [<timeout in second (int)>]
	└─ display current client default timeout or save one if it's set (0 to disable)

	┌─ console_version
	└─ return console version

	┌─ tls_config
	└─ display TLS client configuration

	┌─ help
	└─ display this help
`

	if c.GetExtraHelp() != "" {
		h += fmt.Sprintf("\n%s\n", c.GetExtraHelp())
	}

	if c.ctxCall == ConsoleCall {
		h += `
	┌─ exit
	└─ exit the console
`
	}

	return h + "\n", nil
}
