// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/www.proto
package remotecli

import (
	"bytes"
	"fmt"

	pb "github.com/hugdubois/ah-svc-www/pb"
)

func (c *remoteCli) cmdServicesStatus(args []string) (string, error) {
	ctx, cancel := c.GetTimeoutContext(c.GetDefaultTimeout())
	defer cancel()

	l, err := c.c.ServicesStatus(ctx, &pb.EmptyMessage{})
	if err != nil {
		return "", fmt.Errorf("ServicesStatus service call fail - %v", err)
	}

	var buffer bytes.Buffer
	var eFlag, eMsg string

	buffer.WriteString("Services status:\n")
	for _, svc := range l.GetServices() {
		switch svc.GetStatus() {
		case pb.ServiceStatus_UNAVAILABLE:
			eFlag = "ERR"
			eMsg = " - " + svc.GetEMsg()
		case pb.ServiceStatus_OK:
			eFlag = "OK"
			eMsg = ""
		}
		buffer.WriteString(fmt.Sprintf("[%s] %s (%s)%s\n",
			eFlag, svc.GetName(), svc.GetVersion(), eMsg))
	}

	return buffer.String(), nil
}
