// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/www.proto
package functest

import (
	"fmt"
)

func TestRsvpCreation(config FunctionalTestConfig) (failures []TestFailure) {
	client, ctx, err := grpcClient(config)
	if err != nil {
		failures = append(failures, TestFailure{Procedure: "RsvpCreation", Message: fmt.Sprintf("gRPC client initialization error (%v)", err)})
		return failures
	}
	defer client.Close()

	var testCaseResults []*TestCaseResult
	reqs, extras, err := testGetRsvpCreationRequest(config)
	if err != nil {
		failures = append(failures, TestFailure{Procedure: "RsvpCreation", Message: fmt.Sprintf("HTTP testGetRsvpCreationRequest error (%v)", err)})
		return failures
	}

	for _, req := range reqs {
		res, err := client.GetGRPCClient().RsvpCreation(ctx, req)
		testCaseResults = append(testCaseResults, &TestCaseResult{req, res, err})
	}

	return testRsvpCreationResponse(config, FUNCTEST_GRPC, testCaseResults, extras)
}
