// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/www.proto
package service

import (
	"testing"

	"golang.org/x/net/context"

	pb "github.com/hugdubois/ah-svc-www/pb"
)

func TestVersion(t *testing.T) {
	versionResponse, err := cli.Version(context.Background(), &pb.EmptyMessage{})

	if err != nil {
		t.Errorf("Error on calling Version: %v", err)
	}

	if versionResponse.GetName() != name {
		t.Errorf("Expected \"%s\" in Name field, got \"%s\"", name, versionResponse.GetName())
	}

	if versionResponse.GetVersion() != svc.Version {
		t.Errorf("Expected \"%s\" in Version field, got \"%s\"", svc.Version, versionResponse.GetVersion())
	}
}
