// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/www.proto
package service

import (
	"github.com/fullstorydev/grpchan"
	"github.com/jinzhu/gorm"
	// END SUB-SERVICES DEFINITION : import-pb
)

// Implements of wwwServer
type wwwServer struct {
	version             string
	subServicesRegistry grpchan.ServiceRegistry
	inProcessChannel    grpchan.Channel
	jwtSecret           string
	caCertificate       string
	certificate         string
	privateKey          string

	// EXTRA : var
	sqliteDataSourceName string
	sqliteHandle         *gorm.DB

	// END EXTRA : var

	// SUB-SERVICES DEFINITION : var-address
	// svc{{SubServiceNamePascalCase}}Address string
	// END SUB-SERVICES DEFINITION : var-address

	// SUB-SERVICES DEFINITION : var-client
	// svc{{SubServiceNamePascalCase}}GrpcClient svc{{SubServiceNamePascalCase}}Pb.{{SubServiceNamePascalCase}}Client
	// END SUB-SERVICES DEFINITION : var-client
}
