// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/www.proto
package service

//import (
//	log "github.com/sirupsen/logrus"
//	// SUB-SERVICES DEFINITION : import-Client
//	// svc{{SubServiceNamePascalCase}}Client "github.com/hugdubois/ah-svc-{{SubServiceNameKebabCase}}/client"
// END SUB-SERVICES DEFINITION : import-client
//)

const grpcTimeout = 5

// SUB-SERVICES DEFINITION : func-init

// END SUB-SERVICES DEFINITION : func-init
