// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/www.proto
package service

import (
	"github.com/jinzhu/gorm"
	log "github.com/sirupsen/logrus"
)

type gormLogger struct{}

func (*gormLogger) Print(v ...interface{}) {
	if v[0] == "sql" {
		log.WithFields(log.Fields{"module": "gorm", "type": "sql"}).Debug(v[3])
	}
	if v[0] == "log" {
		log.WithFields(log.Fields{"module": "gorm", "type": "log"}).Warn(v[2])
	}
}

// initDatabaseHandle initializes the databases handles of the server.
func (s *wwwServer) initDatabaseHandle() error {
	// establish the connection if it's not ready
	if s.sqliteHandle == nil {
		dsn := s.sqliteDataSourceName

		sqliteHandle, err := gorm.Open("sqlite3", dsn)
		if err != nil {
			log.WithFields(log.Fields{
				"DSN": s.sqliteDataSourceName,
			}).Infof("database connection error: %v", err)
			return err
		}
		sqliteHandle.SetLogger(&gormLogger{})
		sqliteHandle.LogMode(true)
		s.sqliteHandle = sqliteHandle
	}

	// ping the database server
	err := s.sqliteHandle.DB().Ping()
	if err != nil {
		return err
	}
	return nil
}

func (s *wwwServer) closeDatabaseHandle() error {
	// close the connection if it's not empty
	if s.sqliteHandle != nil {
		err := s.sqliteHandle.Close()
		if err != nil {
			return err
		}
		s.sqliteHandle = nil
	}

	return nil
}
