#!/bin/sh
# Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
# source: pb/www.proto
#
# Usage :
#   run.sh [force inprocess execution<1|true|t|yes|y|inprocgrpc>]
#
# if ./run-env.sh exists it's loaded. So you can define custom environment variables inside this file
#
#   HUGDUBOIS_PATH="$GOPATH/src/github.com/hugdubois"
#   HUGDUBOIS_EXEC_TYPE="make" # go, make
#   HUGDUBOIS_JWT_SECRET=""
#   AH_SVC_WWW_ADDRESS=":13000"

########
# init #
########
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

if [ -f "$SCRIPTPATH/run-env.sh" ];
then
	. "$SCRIPTPATH/run-env.sh"
fi;

###########################################
# set environment variables if not exists #
###########################################
HUGDUBOIS_PATH="$GOPATH/src/github.com/hugdubois"
[ -z "$HUGDUBOIS_EXEC_TYPE" ] && HUGDUBOIS_EXEC_TYPE="make" # go, make
[ -z "$HUGDUBOIS_JWT_SECRET" ] && HUGDUBOIS_JWT_SECRET=""
[ -z "$AH_SVC_WWW_ADDRESS" ] && AH_SVC_WWW_ADDRESS=":13000"

##################
# launch console #
##################
cd $HUGDUBOIS_PATH/ah-svc-www
AH_SVC_WWW_CONSOLE_OPTS='console --address="$AH_SVC_WWW_ADDRESS"
'
case $HUGDUBOIS_EXEC_TYPE in
	"go")
		CMD='CGO_ENABLED=0 go run
			-ldflags "-extldflags \"-lm -lstdc++ -static\""
			-ldflags "-X github.com/hugdubois/ah-svc-www/service.version=$(cat VERSION) -X github.com/hugdubois/ah-svc-www/service.name=ah-svc-www"
			main.go'
		AH_SVC_WWW_CONSOLE_OPTS_JWT=''
		[ -z "$HUGDUBOIS_JWT_SECRET" ] || AH_SVC_WWW_CONSOLE_OPTS_JWT='--jwt $('$CMD' token -k "$HUGDUBOIS_JWT_SECRET")'
		EXEC=$CMD" "$AH_SVC_WWW_CONSOLE_OPTS" "$AH_SVC_WWW_CONSOLE_OPTS_JWT
		echo "[Exec] - "$EXEC
		eval $EXEC
		break
		;;
	"make")
		CMD='_build/ah-svc-www'
		AH_SVC_WWW_CONSOLE_OPTS_JWT=''
		[ -z "$HUGDUBOIS_JWT_SECRET" ] || AH_SVC_WWW_CONSOLE_OPTS_JWT='--jwt $('$CMD' token -k "$HUGDUBOIS_JWT_SECRET")'
		EXEC="make && "$CMD" "$AH_SVC_WWW_CONSOLE_OPTS" "$AH_SVC_WWW_CONSOLE_OPTS_JWT
		echo "[Exec] - "$EXEC
		eval $EXEC
		break
		;;
	*)
		echo "[Erro] - unknow $HUGDUBOIS_EXEC_TYPE value for HUGDUBOIS_EXEC_TYPE [go|make] allowed"
		echo "[Fail] - to launch server : "
		echo "[Fail] - ah-svc-www " $AH_SVC_WWW_CONSOLE_OPTS
		eval echo "[Fail] - ah-svc-www "$AH_SVC_WWW_CONSOLE_OPTS
		;;
esac
