#!/bin/sh
# Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
# source: pb/www.proto
#
# Usage :
#   run.sh [force inprocess execution<1|true|t|yes|y|inprocgrpc>]
#
# if ./run-env.sh exists it's loaded. So you can define custom environment variables inside this file
#
#   HUGDUBOIS_PATH="$GOPATH/src/github.com/hugdubois"
#   HUGDUBOIS_EXEC_TYPE="make" # go, make
#   HUGDUBOIS_JWT_SECRET=""
#   AH_SVC_WWW_ADDRESS=":13000"
#   AH_SVC_WWW_SQLITE_MIGRATE="true"

#   AH_SVC_WWW_SQLITE_DB_DSN="/tmp/ah_svc_www.sqlite3.db"



########
# init #
########
trap killgroup 2

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

GOARCH=$(go env GOARCH)
GOOS=$(go env GOOS)

killgroup(){
	echo killing...
	kill 0
}

if [ -s "$SCRIPTPATH/run-env.sh" ];
then
	. "$SCRIPTPATH/run-env.sh"
fi;

###########################################
# set environment variables if not exists #
###########################################
HUGDUBOIS_PATH="$GOPATH/src/github.com/hugdubois"
[ -z "$HUGDUBOIS_EXEC_TYPE" ] && HUGDUBOIS_EXEC_TYPE="make" # go, make
[ -z "$HUGDUBOIS_JWT_SECRET" ] && HUGDUBOIS_JWT_SECRET=""
[ -z "$AH_SVC_WWW_ADDRESS" ] && AH_SVC_WWW_ADDRESS=":13000"
[ -z "$AH_SVC_WWW_SQLITE_MIGRATE" ] && AH_SVC_WWW_SQLITE_MIGRATE="true"
if [ -z "$AH_SVC_WWW_SQLITE_DB_DSN" ]
then
	AH_SVC_WWW_SQLITE_DB_DSN="/tmp/ah_svc_www.sqlite3.db"
fi;



############################################
# define excution's flags of each services #
############################################
case "$1" in
	"1"|1|"yes"|"y"|"true"|"t"|"YES"|"Y"|"TRUE"|"T")
		echo "[Warn] - Force inprocess subservices execution"
		;;
esac
AH_SVC_WWW_SERVER_OPTS='serve
	-d
	--jwt-secret="$HUGDUBOIS_JWT_SECRET"'

AH_SVC_WWW_SERVER_OPTS_MIGRATE=''

case "$AH_SVC_WWW_SQLITE_MIGRATE" in
	"true"|"1"|1|true|"t"|"yes"|"y")
		AH_SVC_WWW_SERVER_OPTS_MIGRATE="$AH_SVC_WWW_SERVER_OPTS_MIGRATE --sqlite-migrate"
	;;
esac

AH_SVC_WWW_SERVER_OPTS_DSN='--sqlite-dsn="$AH_SVC_WWW_SQLITE_DB_DSN"
'


AH_SVC_WWW_SERVER_OPTS_EXTRAFLAGS=''
AH_SVC_WWW_SERVER_OPTS_ADDR='--address="$AH_SVC_WWW_ADDRESS"
'
AH_SVC_WWW_SERVER_OPTS_ADDR_EMBED='--svc-www-address="$AH_SVC_WWW_ADDRESS"
'


AH_SVC_WWW_SERVER_OPTS=$AH_SVC_WWW_SERVER_OPTS" "$AH_SVC_WWW_SERVER_OPTS_MIGRATE
AH_SVC_WWW_SERVER_OPTS=$AH_SVC_WWW_SERVER_OPTS" "$AH_SVC_WWW_SERVER_OPTS_DSN
AH_SVC_WWW_SERVER_OPTS=$AH_SVC_WWW_SERVER_OPTS" "$AH_SVC_WWW_SERVER_OPTS_EXTRAFLAGS
AH_SVC_WWW_SERVER_OPTS=$AH_SVC_WWW_SERVER_OPTS" "$AH_SVC_WWW_SERVER_OPTS_ADDR



##############################
# launch all needed services #
##############################

cd $HUGDUBOIS_PATH/ah-svc-www
case $HUGDUBOIS_EXEC_TYPE in
	"go")
		CMD='CGO_ENABLED=0 go run
			-ldflags "-extldflags \"-lm -lstdc++ -static\""
			-ldflags "-X github.com/hugdubois/ah-svc-www/service.version=$(cat VERSION) -X github.com/hugdubois/ah-svc-www/service.name=ah-svc-www"
			main.go'
		EXEC=$CMD" "$AH_SVC_WWW_SERVER_OPTS
		echo "[Exec] - "$EXEC
		eval $EXEC
		break
	;;
	"make")
		CMD='make && _build/ah-svc-www'
		EXEC=$CMD" "$AH_SVC_WWW_SERVER_OPTS
		echo "[Exec] - "$EXEC
		eval $EXEC
		break
	;;
	*)
		echo "[Erro] - unknow $HUGDUBOIS_EXEC_TYPE value for HUGDUBOIS_EXEC_TYPE [go|make] allowed"
		echo "[Fail] - to launch server : "
		echo "[Fail] - ah-svc-www " $AH_SVC_WWW_SERVER_OPTS
		eval echo "[Fail] - ah-svc-www "$AH_SVC_WWW_SERVER_OPTS
	;;
esac

wait
