// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/www.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/www.proto

It has these top-level messages:
	EmptyMessage
	VersionResponse
	ServiceStatus
	ServicesStatusList
	RsvpCreationRequest
	RsvpInfo
	RsvpCreationResponse
*/
package pb

import faker "github.com/dmgk/faker"
import locales "github.com/dmgk/faker/locales"
import rand "math/rand"
import strings "strings"
import time "time"
import uuid "github.com/google/uuid"
import proto "github.com/gogo/protobuf/proto"
import golang_proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/gomeet/go-proto-gomeetfaker"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func GomeetFakerRand() *rand.Rand {
	seed := time.Now().UnixNano()
	return rand.New(rand.NewSource(seed))
}
func init() {
	GomeetFakerSetLocale("en")
}

func GomeetFakerSetLocale(l string) {
	switch l {
	case "de":
		faker.Locale = locales.De
	case "de-at":
		faker.Locale = locales.De_AT
	case "de-ch":
		faker.Locale = locales.De_CH
	case "en":
		faker.Locale = locales.En
	case "en-au":
		faker.Locale = locales.En_AU
	case "en-au-ocker":
		faker.Locale = locales.En_AU_OCKER
	case "en-bork":
		faker.Locale = locales.En_BORK
	case "en-ca":
		faker.Locale = locales.En_CA
	case "en-gb":
		faker.Locale = locales.En_GB
	case "en-ind":
		faker.Locale = locales.En_IND
	case "en-nep":
		faker.Locale = locales.En_NEP
	case "en-us":
		faker.Locale = locales.En_US
	case "es":
		faker.Locale = locales.Es
	case "fa":
		faker.Locale = locales.Fa
	case "fr":
		faker.Locale = locales.Fr
	case "it":
		faker.Locale = locales.It
	case "ja":
		faker.Locale = locales.Ja
	case "ko":
		faker.Locale = locales.Ko
	case "nb-no":
		faker.Locale = locales.Nb_NO
	case "nl":
		faker.Locale = locales.Nl
	case "pl":
		faker.Locale = locales.Pl
	case "pt-br":
		faker.Locale = locales.Pt_BR
	case "ru":
		faker.Locale = locales.Ru
	case "sk":
		faker.Locale = locales.Sk
	case "sv":
		faker.Locale = locales.Sv
	case "vi":
		faker.Locale = locales.Vi
	case "zh-cn":
		faker.Locale = locales.Zh_CN
	case "zh-tw":
		faker.Locale = locales.Zh_TW
	default:
		faker.Locale = locales.En
	}
}
func NewEmptyMessageGomeetFaker() *EmptyMessage {
	this := &EmptyMessage{}
	return this
}

func NewVersionResponseGomeetFaker() *VersionResponse {
	this := &VersionResponse{}
	this.Name = faker.App().Name()
	this.Version = faker.App().Version()
	return this
}

func NewServiceStatusGomeetFaker() *ServiceStatus {
	this := &ServiceStatus{}
	this.Name = faker.App().Name()
	this.Version = faker.App().Version()
	// this.Status is a string or bytes without gommetfaker rules so faker.Lorem().Lorem() is used
	this.Status = ServiceStatus_Status([]int32{0, 1}[GomeetFakerRand().Intn(2)])
	// this.EMsg // skipped by skip rules
	return this
}

func NewServicesStatusListGomeetFaker() *ServicesStatusList {
	this := &ServicesStatusList{}
	for i := 0; i < 3; i++ {
		aCurrentServices := NewServiceStatusGomeetFaker()
		this.Services = append(this.Services, aCurrentServices)
	}
	return this
}

func NewRsvpCreationRequestGomeetFaker() *RsvpCreationRequest {
	this := &RsvpCreationRequest{}
	this.Names = strings.Join(faker.Lorem().Words(6), " ")
	this.Email = faker.Internet().Email()
	this.Presence = true
	this.ChildrenNameAge = strings.Join(faker.Lorem().Words(6), " ")
	this.Housing = true
	this.Music = strings.Join(faker.Lorem().Words(6), " ")
	this.Brunch = true
	return this
}

func NewRsvpInfoGomeetFaker() *RsvpInfo {
	this := &RsvpInfo{}
	this.Uuid = uuid.New().String()
	this.Names = strings.Join(faker.Lorem().Words(6), " ")
	this.Email = faker.Internet().Email()
	this.Presence = true
	this.ChildrenNameAge = strings.Join(faker.Lorem().Words(6), " ")
	this.Housing = true
	this.Music = strings.Join(faker.Lorem().Words(6), " ")
	this.Brunch = true
	this.CreatedAt = time.Now().Format("2006-01-02T15:04:05Z07:00")
	this.UpdatedAt = time.Now().Format("2006-01-02T15:04:05Z07:00")
	this.DeletedAt = time.Now().Format("2006-01-02T15:04:05Z07:00")
	return this
}

func NewRsvpCreationResponseGomeetFaker() *RsvpCreationResponse {
	this := &RsvpCreationResponse{}
	this.Ok = true
	this.Info = NewRsvpInfoGomeetFaker()
	return this
}
