// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/www.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/www.proto

It has these top-level messages:
	EmptyMessage
	VersionResponse
	ServiceStatus
	ServicesStatusList
	EchoRequest
	EchoResponse
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import golang_proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/gomeet/go-proto-gomeetfaker"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ServiceStatus_Status int32

const (
	ServiceStatus_OK          ServiceStatus_Status = 0
	ServiceStatus_UNAVAILABLE ServiceStatus_Status = 1
)

var ServiceStatus_Status_name = map[int32]string{
	0: "OK",
	1: "UNAVAILABLE",
}
var ServiceStatus_Status_value = map[string]int32{
	"OK":          0,
	"UNAVAILABLE": 1,
}

func (x ServiceStatus_Status) String() string {
	return proto.EnumName(ServiceStatus_Status_name, int32(x))
}
func (ServiceStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptorWww, []int{2, 0} }

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptorWww, []int{0} }

// VersionMessage represents a version message
type VersionResponse struct {
	// Id represents the message identifier.
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptorWww, []int{1} }

func (m *VersionResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// SeviceStatus represents a sub services status message
type ServiceStatus struct {
	Name    string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status  ServiceStatus_Status `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.hugdubois.www.ServiceStatus_Status" json:"status,omitempty"`
	EMsg    string               `protobuf:"bytes,4,opt,name=e_msg,json=eMsg,proto3" json:"e_msg,omitempty"`
}

func (m *ServiceStatus) Reset()                    { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string            { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()               {}
func (*ServiceStatus) Descriptor() ([]byte, []int) { return fileDescriptorWww, []int{2} }

func (m *ServiceStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceStatus) GetStatus() ServiceStatus_Status {
	if m != nil {
		return m.Status
	}
	return ServiceStatus_OK
}

func (m *ServiceStatus) GetEMsg() string {
	if m != nil {
		return m.EMsg
	}
	return ""
}

// ServicesStatusList is the sub services status list
type ServicesStatusList struct {
	Services []*ServiceStatus `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServicesStatusList) Reset()                    { *m = ServicesStatusList{} }
func (m *ServicesStatusList) String() string            { return proto.CompactTextString(m) }
func (*ServicesStatusList) ProtoMessage()               {}
func (*ServicesStatusList) Descriptor() ([]byte, []int) { return fileDescriptorWww, []int{3} }

func (m *ServicesStatusList) GetServices() []*ServiceStatus {
	if m != nil {
		return m.Services
	}
	return nil
}

// EchoRequest represents a simple message sent to the Echo service.
type EchoRequest struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptorWww, []int{4} }

func (m *EchoRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EchoRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// EchoResponse represents a simple message that the Echo service return.
type EchoResponse struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptorWww, []int{5} }

func (m *EchoResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EchoResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "grpc.hugdubois.www.EmptyMessage")
	golang_proto.RegisterType((*EmptyMessage)(nil), "grpc.hugdubois.www.EmptyMessage")
	proto.RegisterType((*VersionResponse)(nil), "grpc.hugdubois.www.VersionResponse")
	golang_proto.RegisterType((*VersionResponse)(nil), "grpc.hugdubois.www.VersionResponse")
	proto.RegisterType((*ServiceStatus)(nil), "grpc.hugdubois.www.ServiceStatus")
	golang_proto.RegisterType((*ServiceStatus)(nil), "grpc.hugdubois.www.ServiceStatus")
	proto.RegisterType((*ServicesStatusList)(nil), "grpc.hugdubois.www.ServicesStatusList")
	golang_proto.RegisterType((*ServicesStatusList)(nil), "grpc.hugdubois.www.ServicesStatusList")
	proto.RegisterType((*EchoRequest)(nil), "grpc.hugdubois.www.EchoRequest")
	golang_proto.RegisterType((*EchoRequest)(nil), "grpc.hugdubois.www.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "grpc.hugdubois.www.EchoResponse")
	golang_proto.RegisterType((*EchoResponse)(nil), "grpc.hugdubois.www.EchoResponse")
	proto.RegisterEnum("grpc.hugdubois.www.ServiceStatus_Status", ServiceStatus_Status_name, ServiceStatus_Status_value)
	golang_proto.RegisterEnum("grpc.hugdubois.www.ServiceStatus_Status", ServiceStatus_Status_name, ServiceStatus_Status_value)
}
func (this *EmptyMessage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EmptyMessage)
	if !ok {
		that2, ok := that.(EmptyMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *VersionResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VersionResponse)
	if !ok {
		that2, ok := that.(VersionResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	return true
}
func (this *ServiceStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServiceStatus)
	if !ok {
		that2, ok := that.(ServiceStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.EMsg != that1.EMsg {
		return false
	}
	return true
}
func (this *ServicesStatusList) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServicesStatusList)
	if !ok {
		that2, ok := that.(ServicesStatusList)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Services) != len(that1.Services) {
		return false
	}
	for i := range this.Services {
		if !this.Services[i].Equal(that1.Services[i]) {
			return false
		}
	}
	return true
}
func (this *EchoRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EchoRequest)
	if !ok {
		that2, ok := that.(EchoRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if this.Content != that1.Content {
		return false
	}
	return true
}
func (this *EchoResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EchoResponse)
	if !ok {
		that2, ok := that.(EchoResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if this.Content != that1.Content {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Www service

type WwwClient interface {
	// Version method receives no paramaters and returns a version message.
	Version(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*VersionResponse, error)
	// ServicesStatus method receives no paramaters and returns all services status message
	ServicesStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServicesStatusList, error)
	// Echo method receives a simple message and returns it.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type wwwClient struct {
	cc *grpc.ClientConn
}

func NewWwwClient(cc *grpc.ClientConn) WwwClient {
	return &wwwClient{cc}
}

func (c *wwwClient) Version(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/grpc.hugdubois.www.Www/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wwwClient) ServicesStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServicesStatusList, error) {
	out := new(ServicesStatusList)
	err := grpc.Invoke(ctx, "/grpc.hugdubois.www.Www/ServicesStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wwwClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/grpc.hugdubois.www.Www/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Www service

type WwwServer interface {
	// Version method receives no paramaters and returns a version message.
	Version(context.Context, *EmptyMessage) (*VersionResponse, error)
	// ServicesStatus method receives no paramaters and returns all services status message
	ServicesStatus(context.Context, *EmptyMessage) (*ServicesStatusList, error)
	// Echo method receives a simple message and returns it.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func RegisterWwwServer(s *grpc.Server, srv WwwServer) {
	s.RegisterService(&_Www_serviceDesc, srv)
}

func _Www_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WwwServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.hugdubois.www.Www/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WwwServer).Version(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Www_ServicesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WwwServer).ServicesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.hugdubois.www.Www/ServicesStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WwwServer).ServicesStatus(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Www_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WwwServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.hugdubois.www.Www/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WwwServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Www_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.hugdubois.www.Www",
	HandlerType: (*WwwServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Www_Version_Handler,
		},
		{
			MethodName: "ServicesStatus",
			Handler:    _Www_ServicesStatus_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _Www_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/www.proto",
}

func NewPopulatedEmptyMessage(r randyWww, easy bool) *EmptyMessage {
	this := &EmptyMessage{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedVersionResponse(r randyWww, easy bool) *VersionResponse {
	this := &VersionResponse{}
	this.Name = string(randStringWww(r))
	this.Version = string(randStringWww(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedServiceStatus(r randyWww, easy bool) *ServiceStatus {
	this := &ServiceStatus{}
	this.Name = string(randStringWww(r))
	this.Version = string(randStringWww(r))
	this.Status = ServiceStatus_Status([]int32{0, 1}[r.Intn(2)])
	this.EMsg = string(randStringWww(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedServicesStatusList(r randyWww, easy bool) *ServicesStatusList {
	this := &ServicesStatusList{}
	if r.Intn(10) != 0 {
		v1 := r.Intn(5)
		this.Services = make([]*ServiceStatus, v1)
		for i := 0; i < v1; i++ {
			this.Services[i] = NewPopulatedServiceStatus(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedEchoRequest(r randyWww, easy bool) *EchoRequest {
	this := &EchoRequest{}
	this.Uuid = string(randStringWww(r))
	this.Content = string(randStringWww(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedEchoResponse(r randyWww, easy bool) *EchoResponse {
	this := &EchoResponse{}
	this.Uuid = string(randStringWww(r))
	this.Content = string(randStringWww(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyWww interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneWww(r randyWww) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringWww(r randyWww) string {
	v2 := r.Intn(100)
	tmps := make([]rune, v2)
	for i := 0; i < v2; i++ {
		tmps[i] = randUTF8RuneWww(r)
	}
	return string(tmps)
}
func randUnrecognizedWww(r randyWww, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldWww(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldWww(dAtA []byte, r randyWww, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateWww(dAtA, uint64(key))
		v3 := r.Int63()
		if r.Intn(2) == 0 {
			v3 *= -1
		}
		dAtA = encodeVarintPopulateWww(dAtA, uint64(v3))
	case 1:
		dAtA = encodeVarintPopulateWww(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateWww(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateWww(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateWww(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateWww(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}

func init() { proto.RegisterFile("pb/www.proto", fileDescriptorWww) }
func init() { golang_proto.RegisterFile("pb/www.proto", fileDescriptorWww) }

var fileDescriptorWww = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0x76, 0xb2, 0x69, 0xb6, 0x9d, 0xae, 0x6d, 0x1d, 0x84, 0xc6, 0xa5, 0x6c, 0xb7, 0x29, 0xca,
	0x52, 0xd8, 0x0c, 0xad, 0x22, 0xa2, 0x08, 0x76, 0xa1, 0x88, 0xd8, 0x6a, 0xc9, 0xea, 0x0a, 0xde,
	0x48, 0x92, 0x9d, 0x66, 0x43, 0x9b, 0x4c, 0xcc, 0x4c, 0x32, 0x88, 0x77, 0x7d, 0x05, 0xdf, 0xc0,
	0x2b, 0x2f, 0xf6, 0x01, 0x7a, 0xe9, 0xf5, 0xde, 0x89, 0xbe, 0x80, 0xd5, 0x87, 0xf0, 0x52, 0x9c,
	0x24, 0xdb, 0x6c, 0x5d, 0x7f, 0x40, 0xaf, 0x72, 0xfe, 0xbe, 0xf3, 0x65, 0xce, 0x77, 0x0e, 0xac,
	0x45, 0x0e, 0x16, 0x42, 0x98, 0x51, 0x4c, 0x39, 0x45, 0xc8, 0x8b, 0x23, 0xd7, 0x1c, 0x24, 0x5e,
	0x3f, 0x71, 0xa8, 0xcf, 0x4c, 0x21, 0x44, 0x7d, 0xc5, 0xa3, 0xd4, 0x3b, 0x22, 0xd8, 0x8e, 0x7c,
	0x6c, 0x87, 0x21, 0xe5, 0x36, 0xf7, 0x69, 0xc8, 0x32, 0x44, 0xfd, 0xa6, 0xe7, 0xf3, 0x41, 0xe2,
	0x98, 0x2e, 0x0d, 0x70, 0x20, 0x7c, 0x7e, 0x48, 0x05, 0xf6, 0x68, 0x5b, 0x26, 0xdb, 0xa9, 0x7d,
	0xe4, 0xf7, 0x6d, 0x4e, 0x63, 0x86, 0xc7, 0x66, 0x8e, 0xbb, 0x55, 0xc2, 0x79, 0x34, 0x20, 0x84,
	0x9f, 0xc1, 0x32, 0xff, 0xc0, 0x3e, 0x24, 0x31, 0x2e, 0xd9, 0x39, 0xb2, 0x3d, 0x81, 0xf4, 0x28,
	0x96, 0x61, 0x27, 0x39, 0x90, 0x9e, 0x74, 0xa4, 0x95, 0x95, 0x1b, 0x0b, 0xb0, 0xb6, 0x13, 0x44,
	0xfc, 0xd5, 0x1e, 0x61, 0xcc, 0xf6, 0x88, 0xd1, 0x85, 0x8b, 0x3d, 0x12, 0x33, 0x9f, 0x86, 0x16,
	0x61, 0x11, 0x0d, 0x19, 0x41, 0x2b, 0x50, 0x0d, 0xed, 0x80, 0xe8, 0xa0, 0x09, 0x5a, 0x73, 0x9d,
	0xd9, 0xd1, 0x50, 0x53, 0x37, 0x94, 0x25, 0x60, 0xc9, 0x28, 0x32, 0x60, 0x35, 0xcd, 0x00, 0xba,
	0x52, 0x2e, 0xd0, 0x81, 0x55, 0x24, 0x8c, 0x4f, 0x00, 0x5e, 0xec, 0x92, 0x38, 0xf5, 0x5d, 0xd2,
	0xe5, 0x36, 0x4f, 0xd8, 0xbf, 0xf7, 0x44, 0xf7, 0xa0, 0xc6, 0x64, 0x2f, 0xbd, 0xd2, 0x04, 0xad,
	0x85, 0xad, 0x96, 0xf9, 0xb3, 0x38, 0xe6, 0x04, 0xa9, 0x99, 0x7d, 0xac, 0x1c, 0x87, 0x56, 0xe0,
	0x0c, 0x79, 0x11, 0x30, 0x4f, 0x57, 0x25, 0x47, 0x75, 0x34, 0xd4, 0x2a, 0x27, 0x00, 0x58, 0x2a,
	0xd9, 0x63, 0x9e, 0xb1, 0x06, 0xb5, 0xfc, 0x5f, 0x35, 0xa8, 0x3c, 0x7e, 0xb8, 0x74, 0x01, 0x2d,
	0xc2, 0xf9, 0xa7, 0x8f, 0xb6, 0x7b, 0xdb, 0x0f, 0x76, 0xb7, 0x3b, 0xbb, 0x3b, 0x4b, 0xc0, 0xe8,
	0x42, 0x94, 0x13, 0xb0, 0xac, 0x74, 0xd7, 0x67, 0x1c, 0xdd, 0x85, 0xb3, 0x2c, 0x8f, 0xea, 0xa0,
	0x59, 0x69, 0xcd, 0x6f, 0xad, 0xfd, 0xf1, 0xd7, 0xac, 0x31, 0xc4, 0xb0, 0xe0, 0xfc, 0x8e, 0x3b,
	0xa0, 0x16, 0x79, 0x99, 0x10, 0xc6, 0x51, 0x03, 0xaa, 0x49, 0xe2, 0xf7, 0xf3, 0x41, 0xc1, 0xd1,
	0x50, 0xd3, 0x90, 0x8a, 0x94, 0xde, 0x0d, 0x4b, 0xc6, 0xd1, 0x3a, 0xac, 0xba, 0x34, 0xe4, 0x24,
	0xe4, 0xf9, 0xa8, 0xe6, 0x46, 0x43, 0x6d, 0xe6, 0x18, 0x28, 0xfb, 0xc0, 0x2a, 0x32, 0x46, 0x17,
	0xd6, 0xb2, 0x9e, 0xb9, 0xa2, 0xff, 0xa3, 0xe9, 0xd6, 0x07, 0x05, 0x56, 0x9e, 0x09, 0x81, 0x7c,
	0x58, 0xcd, 0x37, 0x06, 0x35, 0xa7, 0x3d, 0xb4, 0xbc, 0x5e, 0xf5, 0xf5, 0x69, 0x15, 0xe7, 0x16,
	0xce, 0x58, 0x3e, 0xfe, 0xf8, 0xf5, 0x8d, 0x72, 0x09, 0x2d, 0xca, 0xa3, 0x4a, 0x37, 0x71, 0xa1,
	0xf9, 0x6b, 0xb8, 0x30, 0x39, 0xf0, 0xbf, 0x60, 0xbc, 0xf6, 0x9b, 0xe1, 0x97, 0x64, 0x33, 0x56,
	0x25, 0xe9, 0x15, 0xb4, 0x5c, 0x90, 0x16, 0x8a, 0xe0, 0x7c, 0x5d, 0x1c, 0xa8, 0xfe, 0x18, 0x22,
	0x5a, 0x9d, 0x4a, 0x79, 0x26, 0x59, 0xbd, 0xf9, 0xeb, 0x82, 0xc9, 0x07, 0x1a, 0xb5, 0x82, 0x8b,
	0xb8, 0x03, 0x7a, 0x1b, 0x6c, 0x74, 0x9e, 0x7c, 0xfb, 0xdc, 0x00, 0xef, 0x4e, 0x1b, 0xe0, 0xe4,
	0xb4, 0x01, 0xde, 0x7f, 0x69, 0x00, 0x78, 0xd9, 0xa5, 0xc1, 0xb9, 0x56, 0xe9, 0xe6, 0xf3, 0xab,
	0xa5, 0x23, 0x1f, 0x27, 0xb1, 0x3d, 0x68, 0xb3, 0xd4, 0x6d, 0x0b, 0x21, 0x70, 0xe4, 0xdc, 0x89,
	0x9c, 0xb7, 0x8a, 0x7a, 0x7f, 0x6f, 0xbf, 0xe3, 0x68, 0xf2, 0xd4, 0xaf, 0x7f, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0x10, 0x74, 0xbc, 0x95, 0xcd, 0x04, 0x00, 0x00,
}
