// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/www.proto
package models

import (
	"flag"
	"fmt"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"

	log "github.com/sirupsen/logrus"
)

var (
	debugMode bool
	// Main database

	sqliteDSN string
)

func init() {
	// force debug mode
	flag.BoolVar(&debugMode, "d", false, "Force debug mode")

	// Sqlite data source name: http://gorm.io/database.html#connecting-to-a-database
	flag.StringVar(&sqliteDSN, "sqlite-dsn", "", "Sqlite data source file")

	flag.Parse()

	log.SetLevel(log.PanicLevel)
	if debugMode {
		log.SetLevel(log.DebugLevel)
		log.Debug("set log debug level")
	}

	log.WithFields(log.Fields{
		"sqliteDSN": sqliteDSN,
	}).Debug("sqliteDSN flag")

}

func flushDbTest(t *testing.T) {
	var err error

	assert.NotEmpty(t, sqliteDSN, "sqliteDSN is empty")

	err = MigrateSchema(sqliteDSN)

	assert.Nil(t, err, fmt.Sprintf("ah-svc-www - sqlite database migration fail - dsn: %s", sqliteDSN))

	err = Flush(sqliteDSN)

	assert.Nil(t, err, fmt.Sprintf("ah-svc-www - sqlite database migration fail - dsn: %s", sqliteDSN))

}

func TestMain(m *testing.M) {
	r := m.Run()

	os.Exit(r)
}
